sonar.projectKey=bobso0613_replay-parser-service
sonar.organization=bobso0613
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/*.test.ts
sonar.coverage.exclusions=src/index.ts,src/script-fix-persisted-output.ts,src/types/**
sonar.cpd.exclusions=**/*.test.ts,src/index.ts,src/script-fix-persisted-output.ts,src/types/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info